build:
	cargo build -p drasi-bootstrap-sui-deepbook

test:
	cargo test -p drasi-bootstrap-sui-deepbook

integration-test:
	@echo "No standalone integration test target for bootstrap crate"

lint:
	cargo clippy -p drasi-bootstrap-sui-deepbook --all-targets -- -D warnings
