#!/bin/sh
case ":${PATH}:" in
    *:"$HOME/.cargo/bin":*)
        ;;
    *)
        export PATH="$HOME/.cargo/bin:$PATH"
        ;;
esac

# This is the clippy command that will be run by the ci-clippy workflow
# RUSTFLAGS="-Dwarnings -W clippy::print_stdout -W clippy::unwrap_used -A unused -A clippy::module_inception -A clippy::ptr_arg -A clippy::type_complexity" rustup run 1.88.0 cargo clippy --all-targets --all-features

echo "Running cargo fmt..."
cargo fmt -- --check