codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "30...100"
  status:
    project:
      default:
        informational: true
        target: auto
        threshold: 0%
    patch:
      default: false