build:
	cargo build -p drasi-reaction-loki

test:
	cargo test -p drasi-reaction-loki

integration-test:
	cargo test -p drasi-reaction-loki -- --ignored --nocapture

lint:
	cargo clippy -p drasi-reaction-loki --all-targets -- -D warnings
