build:
	cargo build -p drasi-bootstrap-dataverse

lint:
	cargo clippy -p drasi-bootstrap-dataverse --all-targets --all-features

test:
	cargo test -p drasi-bootstrap-dataverse

integration-test:
	cargo test -p drasi-bootstrap-dataverse -- --ignored --nocapture
