build:
	cargo build -p drasi-source-open511

lint:
	cargo clippy -p drasi-source-open511 --all-targets --all-features

test:
	cargo test -p drasi-source-open511

integration-test:
	cargo test -p drasi-source-open511 --test integration_test -- --ignored --nocapture
