{
 "title": "Drasi Loki Overview",
 "tags": [
  "drasi",
  "loki",
  "example"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "sensor_1 Hot Alert",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time({job=\"drasi-example\",query_id=\"persistent-hot-sensors\"} | json | __error__=\"\" | sensor=\"sensor_1\" | keep sensor,active | unwrap active [5m])"
    }
   ]
  },
  {
   "title": "sensor_2 Hot Alert",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time({job=\"drasi-example\",query_id=\"persistent-hot-sensors\"} | json | __error__=\"\" | sensor=\"sensor_2\" | keep sensor,active | unwrap active [5m])"
    }
   ]
  },
  {
   "title": "sensor_3 Hot Alert",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time({job=\"drasi-example\",query_id=\"persistent-hot-sensors\"} | json | __error__=\"\" | sensor=\"sensor_3\" | keep sensor,active | unwrap active [5m])"
    }
   ]
  },
  {
   "title": "sensor_4 Hot Alert",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time({job=\"drasi-example\",query_id=\"persistent-hot-sensors\"} | json | __error__=\"\" | sensor=\"sensor_4\" | keep sensor,active | unwrap active [5m])"
    }
   ]
  },
  {
   "title": "sensor_5 Hot Alert",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time({job=\"drasi-example\",query_id=\"persistent-hot-sensors\"} | json | __error__=\"\" | sensor=\"sensor_5\" | keep sensor,active | unwrap active [5m])"
    }
   ]
  },
  {
   "title": "Sensor Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "last_over_time({job=\"drasi-example\",query_id=\"all-sensors\"} | json | __error__=\"\" | event=~\"ADD|UPDATE\" | unwrap temperature [1m]) by (sensor)"
    }
   ]
  },
  {
   "title": "Drasi Loki Events",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{job=\"drasi-example\"}"
    }
   ]
  }
 ]
}