build:
	cargo build -p cloudflare-radar-dashboard

lint:
	cargo clippy -p cloudflare-radar-dashboard --all-targets --all-features

test:
	cargo test -p cloudflare-radar-dashboard

integration-test:
	cargo test -p cloudflare-radar-dashboard -- --ignored --nocapture
