build:
	cargo build -p drasi-bootstrap-cloudflare-radar

lint:
	cargo clippy -p drasi-bootstrap-cloudflare-radar --all-targets --all-features

test:
	cargo test -p drasi-bootstrap-cloudflare-radar

integration-test:
	cargo test -p drasi-bootstrap-cloudflare-radar -- --ignored --nocapture
