build:
	cargo build -p drasi-bootstrap-here-traffic

lint:
	cargo clippy -p drasi-bootstrap-here-traffic --all-targets --all-features

test:
	cargo test -p drasi-bootstrap-here-traffic

integration-test:
	cargo test -p drasi-bootstrap-here-traffic -- --ignored --nocapture
