name: Rust Lint

on:
  pull_request:
    branches:
      - main
      - feature/*
      - feature-lib
      - release/*

permissions:
  contents: read

jobs:
  lint:
    uses: drasi-project/.github/.github/workflows/rust-lint.yaml@main