name: Run Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - feature/*
      - feature-lib
      - release/*

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read


jobs:
  test:
    uses: drasi-project/.github/.github/workflows/rust-unit-test.yaml@rust195
    with:
      test-command: |
        cargo test --workspace --exclude drasi-host-sdk
        make test-host-sdk
