name: Run Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - feature/*
      - feature-lib
      - release/*

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read


jobs:
  test:
    uses: drasi-project/.github/.github/workflows/rust-unit-test.yaml@main
    with:
      test-command: |
        cargo test --workspace --exclude drasi-host-sdk
        make test-host-sdk

  perf-test:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false

    strategy:
      matrix:
        index: 
          - memory
          - redis
          - rocksdb

    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Show Rust toolchain
      run: rustup show

    - name: Cache Cargo registry
      uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-

    - name: Cache Cargo index
      uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-index-

    - name: Cache Cargo build
      uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-build-
    
    - name: Perf testing
      env:
        REDIS_URL: redis://localhost:6379
        FILE_NAME: perf_test_results_100K_${{matrix.index}}
      run: |
        cd query-perf
        cargo run -- -s all -e ${{matrix.index}} -r ${{matrix.index}} -i 100000 > ${{env.FILE_NAME}}
        cat ${{env.FILE_NAME}}