name: Test Issue Research

on:
  push:
    branches:
      - workflow_call_test

jobs:
  research:
    uses: drasi-project/.github/.github/workflows/drasi-issue-researcher.lock.yml@centralized-workflows
    with:
      issue_url: "https://github.com/ruokun-niu/drasi-core/issues/6"
    secrets: inherit